#!/bin/sh

## Start 'session-manager' if not already running and allow some time for Android system to boot ##
# Always use the host's GLES driver otherwise will cause the following error: #
#       anbox "eglCreateSyncKHR: error 0x3004 (EGL_BAD_ATTRIBUTE)"
if [ -z "$(ps aux | grep 'anbox session-manager' | grep -v grep)" ]; then
	anbox session-manager --gles-driver=host &
	sleep 5s
fi
anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
